In [19]:
import numpy as np
from sklearn import metrics

In [1]:
y = ['cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 
     'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 
     'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 
     'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', ]

In [11]:
y_pred = ['cat', 'cat', 'cat', 'cat', 'cat', 'dog', 'dog', 'dog', 
          'cat', 'cat', 'dog', 'dog', 'dog', 'rabbit',
          'dog', 'dog', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 
         'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit',  'rabbit']

In [12]:
cm = metrics.confusion_matrix(y, y_pred)
cm

array([[ 5,  3,  0],
       [ 2,  3,  1],
       [ 0,  2, 11]])

In [28]:
cm

array([[ 5,  3,  0],
       [ 2,  3,  1],
       [ 0,  2, 11]])

# Accuracy-score

In [29]:
metrics.accuracy_score(y, y_pred)

0.7037037037037037

# Precision-score

In [30]:
precision = metrics.precision_score(y, y_pred, average=None)
precision.T
precision_mean = np.mean(precision)
print(precision)
print(precision_mean)

[0.71428571 0.375      0.91666667]
0.6686507936507936


# Recall-score

In [31]:
recall = metrics.recall_score(y, y_pred, average=None)
recall.T
recall_mean = np.mean(recall)
print(recall)
print(recall_mean)

[0.625      0.5        0.84615385]
0.657051282051282


# F1-score

In [32]:
f1 = metrics.f1_score(y, y_pred, average=None)
f1.T
f1_mean = np.mean(f1)
print(f1)
print(f1_mean)

[0.66666667 0.42857143 0.88      ]
0.6584126984126983


# Classification-report

In [33]:
print(metrics.classification_report(y, y_pred))

              precision    recall  f1-score   support

         cat       0.71      0.62      0.67         8
         dog       0.38      0.50      0.43         6
      rabbit       0.92      0.85      0.88        13

   micro avg       0.70      0.70      0.70        27
   macro avg       0.67      0.66      0.66        27
weighted avg       0.74      0.70      0.72        27



# Curva ROC

In [ ]:
roc_curve = metrics.roc_curve(y_true, y_score)

# Log Loss

In [ ]:
log_loss = metrics.log_loss(y, y_pred)