# Pedro Alves Gonçalves Júnior

In [87]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_distances
from sklearn.metrics.pairwise import cosine_similarity

In [88]:
consulta = 'movie Brazil influence investigation powerful snoopy disgrace'

In [89]:
data = pd.read_csv('../datasets/movie_data.csv')

In [90]:
data.head()

review  sentiment
0  In 1974, the teenager Martha Moxley (Maggie Gr...          1
1  OK... so... I really like Kris Kristofferson a...          0
2  ***SPOILER*** Do not read this, if you think a...          0
3  hi for all the people who have seen this wonde...          1
4  I recently bought the DVD, forgetting just how...          0

In [91]:
docs = data.values[:1000,0]

In [92]:
docs.shape

(1000,)

In [ ]:
docs.append()

In [52]:
count_vectorizer = CountVectorizer(stop_words='english')

In [53]:
matrix_sparse = count_vectorizer.fit_transform(docs)

In [54]:
print(matrix_sparse.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# Similaridade Cosseno

In [64]:
sim_cos = cosine_similarity(matrix_sparse, matrix_sparse[0])

In [70]:
res = sim_cos.reshape(matrix_sparse.shape[0])

In [85]:
res.argsort()[-10:]

array([ 71, 246,  55, 648, 995, 695, 598, 101, 414,   0])

In [83]:
consulta

'movie Brazil influence investigation powerful snoopy disgrace'

In [86]:
docs[0]

'In 1974, the teenager Martha Moxley (Maggie Grace) moves to the high-class area of Belle Haven, Greenwich, Connecticut. On the Mischief Night, eve of Halloween, she was murdered in the backyard of her house and her murder remained unsolved. Twenty-two years later, the writer Mark Fuhrman (Christopher Meloni), who is a former LA detective that has fallen in disgrace for perjury in O.J. Simpson trial and moved to Idaho, decides to investigate the case with his partner Stephen Weeks (Andrew Mitchell) with the purpose of writing a book. The locals squirm and do not welcome them, but with the support of the retired detective Steve Carroll (Robert Forster) that was in charge of the investigation in the 70\'s, they discover the criminal and a net of power and money to cover the murder.<br /><br />"Murder in Greenwich" is a good TV movie, with the true story of a murder of a fifteen years old girl that was committed by a wealthy teenager whose mother was a Kennedy. The powerful and rich famil

In [81]:
docs[746]

"I am a big fan of Larkin's works, I believe that he was amid the greatest 20th century poets. The film itself does a great justice to the bard of Hull. Wonderfully portrayed by all the players in their roles. Bonneville does do a service to the sexually repressed Larkin, he avoids an impression and strays from becoming a caricature. The use of his poetry was the highlight of the piece itself. Rather than acting out the massive intensity with which Larkin felt, the use of his words themselves give a better insight into plot and add a much more sombre but altogether more fascinating atmosphere. Most enjoyable."

In [82]:
docs[732]

"This is film that was actually recommended to me by my dentist, and am I glad he did! The blend of British humor (should I say, Humour?) and the reality of a lost, middle-aged widow trying to maintain her lifestyle were a hoot. Add to that mix the reality of what it takes to actually grow pot (those plants under the bushes were NOT going to make it without the TLC they received), and it is a truly hilarious, yet touching film. I laugh every time I conjure the vision of all the bar patrons sitting in their lawn chairs with sunglasses on counting down the lights! Maybe it's just my Mendocino County blood, but the Brits definitely got this one right!! 10/10"