# Pedro Alves Gonçalves Júnior

In [1]:
import pandas as pd
import numpy as np

In [2]:
cols = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'target']
data = pd.read_csv('../datasets/adult.data', names=cols, na_values=[' ?', 'nan'])

In [3]:
data.head()

age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  target  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [4]:
data.shape

(32561, 15)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         30725 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education-num     32561 non-null int64
marital-status    32561 non-null object
occupation        30718 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital-gain      32561 non-null int64
capital-loss      32561 non-null int64
hours-per-week    32561 non-null int64
native-country    31978 non-null object
target            32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [6]:
data.isna().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
target               0
dtype: int64

In [7]:
data.isna().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
target               0
dtype: int64

In [8]:
data.shape

(32561, 15)

In [9]:
data.drop('education', axis=1, inplace=True)

In [10]:
data.head()

age          workclass  fnlwgt  education-num       marital-status  \
0   39          State-gov   77516             13        Never-married   
1   50   Self-emp-not-inc   83311             13   Married-civ-spouse   
2   38            Private  215646              9             Divorced   
3   53            Private  234721              7   Married-civ-spouse   
4   28            Private  338409             13   Married-civ-spouse   

           occupation    relationship    race      sex  capital-gain  \
0        Adm-clerical   Not-in-family   White     Male          2174   
1     Exec-managerial         Husband   White     Male             0   
2   Handlers-cleaners   Not-in-family   White     Male             0   
3   Handlers-cleaners         Husband   Black     Male             0   
4      Prof-specialty            Wife   Black   Female             0   

   capital-loss  hours-per-week  native-country  target  
0             0              40   United-States   <=50K  
1             0              13   United-States   <=50K  
2             0              40   United-States   <=50K  
3             0              40   United-States   <=50K  
4             0              40            Cuba   <=50K

In [11]:
data['target'] = np.where(data['target'] == ' <=50K', 1, -1)

In [12]:
data.head()

age          workclass  fnlwgt  education-num       marital-status  \
0   39          State-gov   77516             13        Never-married   
1   50   Self-emp-not-inc   83311             13   Married-civ-spouse   
2   38            Private  215646              9             Divorced   
3   53            Private  234721              7   Married-civ-spouse   
4   28            Private  338409             13   Married-civ-spouse   

           occupation    relationship    race      sex  capital-gain  \
0        Adm-clerical   Not-in-family   White     Male          2174   
1     Exec-managerial         Husband   White     Male             0   
2   Handlers-cleaners   Not-in-family   White     Male             0   
3   Handlers-cleaners         Husband   Black     Male             0   
4      Prof-specialty            Wife   Black   Female             0   

   capital-loss  hours-per-week  native-country  target  
0             0              40   United-States       1  
1             0              13   United-States       1  
2             0              40   United-States       1  
3             0              40   United-States       1  
4             0              40            Cuba       1

In [13]:
data = pd.get_dummies(data, columns=['workclass', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country'], drop_first=True)

In [14]:
data.columns

Index(['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss',
       'hours-per-week', 'target', 'workclass_ Local-gov',
       'workclass_ Never-worked', 'workclass_ Private',
       'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc',
       'workclass_ State-gov', 'workclass_ Without-pay',
       'marital-status_ Married-AF-spouse',
       'marital-status_ Married-civ-spouse',
       'marital-status_ Married-spouse-absent',
       'marital-status_ Never-married', 'marital-status_ Separated',
       'marital-status_ Widowed', 'occupation_ Armed-Forces',
       'occupation_ Craft-repair', 'occupation_ Exec-managerial',
       'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners',
       'occupation_ Machine-op-inspct', 'occupation_ Other-service',
       'occupation_ Priv-house-serv', 'occupation_ Prof-specialty',
       'occupation_ Protective-serv', 'occupation_ Sales',
       'occupation_ Tech-support', 'occupation_ Transport-moving',
       'relationship_ 

In [15]:
data.head()

age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0   39   77516             13          2174             0              40   
1   50   83311             13             0             0              13   
2   38  215646              9             0             0              40   
3   53  234721              7             0             0              40   
4   28  338409             13             0             0              40   

   target  workclass_ Local-gov  workclass_ Never-worked  workclass_ Private  \
0       1                     0                        0                   0   
1       1                     0                        0                   0   
2       1                     0                        0                   1   
3       1                     0                        0                   1   
4       1                     0                        0                   1   

   ...  native-country_ Portugal  native-country_ Puerto-Rico  \
0  ...                         0                            0   
1  ...                         0                            0   
2  ...                         0                            0   
3  ...                         0                            0   
4  ...                         0                            0   

   native-country_ Scotland  native-country_ South  native-country_ Taiwan  \
0                         0                      0                       0   
1                         0                      0                       0   
2                         0                      0                       0   
3                         0                      0                       0   
4                         0                      0                       0   

   native-country_ Thailand  native-country_ Trinadad&Tobago  \
0                         0                                0   
1                         0                                0   
2                         0                                0   
3                         0                                0   
4                         0                                0   

   native-country_ United-States  native-country_ Vietnam  \
0                              1                        0   
1                              1                        0   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   native-country_ Yugoslavia  
0                           0  
1                           0  
2                           0  
3                           0  
4                           0  

[5 rows x 83 columns]

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 83 columns):
age                                           32561 non-null int64
fnlwgt                                        32561 non-null int64
education-num                                 32561 non-null int64
capital-gain                                  32561 non-null int64
capital-loss                                  32561 non-null int64
hours-per-week                                32561 non-null int64
target                                        32561 non-null int64
workclass_ Local-gov                          32561 non-null uint8
workclass_ Never-worked                       32561 non-null uint8
workclass_ Private                            32561 non-null uint8
workclass_ Self-emp-inc                       32561 non-null uint8
workclass_ Self-emp-not-inc                   32561 non-null uint8
workclass_ State-gov                          32561 non-null uint8
workclass_ Without-p

In [17]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [18]:
y = data['target'].values
data.drop('target', axis=1, inplace=True)
X = data.values

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

In [20]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((26048, 82), (6513, 82), (26048,), (6513,))

In [21]:
kFold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [22]:
scala = StandardScaler()
X_train_std = scala.fit_transform(X_train)
X_test_std = scala.transform(X_test)

/home/pedim/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/pedim/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/pedim/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


# Perceptron

In [23]:
model_perceptron = Perceptron(max_iter=1000, tol=1e-3)
acc_perceptron = cross_val_score(model_perceptron, X_train_std, y_train, cv=kFold)
acc_perceptron

array([0.80019194, 0.79232246, 0.81497121, 0.80687272, 0.80802457])

In [25]:
np.mean(acc_perceptron)

0.8044765795506006

# Adaline

In [26]:
model_adaline = SGDClassifier(max_iter=1000, tol=1e-3)
acc_adaline = cross_val_score(model_adaline, X_train_std, y_train, cv=kFold)
acc_adaline

array([0.84145873, 0.83454894, 0.84587332, 0.84392398, 0.8414283 ])

In [27]:
np.mean(acc_adaline)

0.841446654597885

# Logistic Regression

In [28]:
model_LR = LogisticRegression(solver='lbfgs')
acc_LR = cross_val_score(model_LR, X_train_std, y_train, cv=kFold)
acc_LR

array([0.85028791, 0.84491363, 0.85777351, 0.85160299, 0.85294682])

In [29]:
np.mean(acc_LR)

0.8515049731215978

# KNN

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=5)
acc_knn = cross_val_score(model_knn, X_train_std, y_train, cv=kFold)
acc_knn

In [ ]:
np.mean(acc_knn)

# Naive Bayes

In [32]:
model_NB = GaussianNB()
acc_NB = cross_val_score(model_NB, X_train_std, y_train, cv=kFold)
acc_NB

array([0.36410749, 0.3756238 , 0.37946257, 0.34709157, 0.30946439])

In [33]:
np.mean(acc_NB)

0.3551499637604928

# SVM

In [ ]:
model_SVM = SVC()
acc_SVM = cross_val_score(model_SVM, X_train_std, y_train, cv=kFold)
acc_SVM

In [ ]:
np.mean(acc_SVC)

# Decision Tree

In [34]:
model_DT = DecisionTreeClassifier()
acc_DT = cross_val_score(model_DT, X_train_std, y_train, cv=kFold)
acc_DT

array([0.80959693, 0.8109405 , 0.80998081, 0.80418506, 0.81032828])

In [35]:
np.mean(acc_DT)

0.8090063152914506

In [40]:
print('Adaline:             ', np.mean(acc_adaline))
print('Árvore de Decisão:   ', np.mean(acc_DT))
print('Regressão Logistica: ', np.mean(acc_LR))
print('Naive Bayes:         ', np.mean(acc_NB))
print('Perceptron:          ', np.mean(acc_perceptron))

Adaline:              0.841446654597885
Árvore de Decisão:    0.8090063152914506
Regressão Logistica:  0.8515049731215978
Naive Bayes:          0.3551499637604928
Perceptron:           0.8044765795506006


# Melhor Resultado
- Regressão Logistica com 85,15 %